#ifndef OPENFIRE_DONGLE_VERSION_H
#define OPENFIRE_DONGLE_VERSION_H

// Current version
#define OPENFIRE_DONGLE_VERSION 6.0
///////#define OPENFIRE_CODENAME "Dawn Sigma rc2"
// #define GIT_HASH
#define OPENFIRE_DONGLE_VERSION_MAJOR 6
#define OPENFIRE_DONGLE_VERSION_MINOR 0
#define OPENFIRE_DONGLE_VERSION_PATCH 0
#define OPENFIRE_DONGLE_VERSION_TYPE "rc2"  // To indicate pre-release (alpha, beta, RC(Release Candidate), stable)

// Current version string
#define OPENFIRE_DONGLE_VERSION_STRING                                                           \
    (String(OPENFIRE_DONGLE_VERSION_MAJOR) + "." + String(OPENFIRE_DONGLE_VERSION_MINOR) + "." + \
     String(OPENFIRE_DONGLE_VERSION_PATCH) + "-" + OPENFIRE_DONGLE_VERSION_TYPE)
// #define OPENFIRE_VERSION_STRING TU_STRING(OPENFIRE_VERSION_MAJOR) "." TU_STRING(OPENFIRE_VERSION_MINOR) "."
// TU_STRING(OPENFIRE_VERSION_PATCH)

// Combined version number
#define OPENFIRE_DONGLE_VERSION_NUMBER \
    (OPENFIRE_DONGLE_VERSION_MAJOR * 10000 + OPENFIRE_DONGLE_VERSION_MINOR * 100 + OPENFIRE_DONGLE_VERSION_PATCH)

// =============== last compatible version =================================

// Last previous compatible version
#define OPENFIRE_DONGLE_COMPATIBLE_MAJOR 4
#define OPENFIRE_DONGLE_COMPATIBLE_MINOR 3
#define OPENFIRE_DONGLE_COMPATIBLE_PATCH 2

// Previous compatible version string
#define OPENFIRE_DONGLE_COMPATIBLE_STRING                                                              \
    (String(OPENFIRE_DONGLE_COMPATIBLE_MAJOR) + "." + String(OPENFIRE_DONGLE_COMPATIBLE_MINOR) + "." + \
     String(OPENFIRE_DONGLE_COMPATIBLE_PATCH))
// #define OPENFIRE_DONGLE_COMPATIBLE_STRING TU_STRING(OPENFIRE_DONGLE_COMPATIBLE_MAJOR) "."
// TU_STRING(OPENFIRE_DONGLE_COMPATIBLE_MINOR) "." TU_STRING(OPENFIRE_DONGLE_COMPATIBLE_PATCH)

// Combined number of the previous compatible version
#define OPENFIRE_DONGLE_COMPATIBLE_NUMBER                                                \
    (OPENFIRE_DONGLE_COMPATIBLE_MAJOR * 10000 + OPENFIRE_DONGLE_COMPATIBLE_MINOR * 100 + \
     OPENFIRE_DONGLE_COMPATIBLE_PATCH)

#endif  // OPENFIRE_DONGLE_VERSION_H
